version: '3.8'

services:
  web:
    # image: linyq1/kol-dashboard-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - API_URL=http://127.0.0.1:8000
    ports:
      - "28082:80"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://127.0.0.1:8000
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped